// @ts-ignore MoonBit build output is generated by `moon build --target js --release`.
import { highlight_bash } from "#moonbit/highlight-bash";

export const highlight: (source: string) => string = highlight_bash;
export default highlight;
