// @ts-ignore MoonBit build output is generated by `moon build --target js --release`.
import { highlight_css } from "#moonbit/highlight-css";

export const highlight: (source: string) => string = highlight_css;
export default highlight;
