// @ts-ignore MoonBit build output is generated by `moon build --target js --release`.
import { highlight_go } from "#moonbit/highlight-go";

export const highlight: (source: string) => string = highlight_go;
export default highlight;
