// @ts-ignore MoonBit build output is generated by `moon build --target js --release`.
import { highlight_html } from "#moonbit/highlight-html";

export const highlight: (source: string) => string = highlight_html;
export default highlight;
