// @ts-ignore MoonBit build output is generated by `moon build --target js --release`.
import { highlight_json } from "#moonbit/highlight-json";

export const highlight: (source: string) => string = highlight_json;
export default highlight;
