// @ts-ignore MoonBit build output is generated by `moon build --target js --release`.
import { highlight_moonbit } from "#moonbit/highlight-moonbit";

export const highlight: (source: string) => string = highlight_moonbit;
export default highlight;
