// @ts-ignore MoonBit build output is generated by `moon build --target js --release`.
import { highlight_rust } from "#moonbit/highlight-rust";

export const highlight: (source: string) => string = highlight_rust;
export default highlight;
