// @ts-ignore MoonBit build output is generated by `moon build --target js --release`.
import { highlight_typescript } from "#moonbit/highlight-typescript";

export const highlight: (source: string) => string = highlight_typescript;
export default highlight;
