#!/usr/bin/env python3
"""Generate deterministic Markdown fixtures used by every implementation."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def block(index: int) -> str:
    variants = (
        f"## Block {index:05d}: Text **bold** *em* and `code`.\n\n",
        f"Block {index:05d} text has **bold**, *em*, and `code`.\n\n",
        f"- Block {index:05d} item with **bold** and `code` text.\n\n",
        f"> Block {index:05d} quote with *em* and `code` text.\n\n",
        f"```text\nBlock {index:05d} code sample 0123456789\n```\n\n",
    )
    return variants[index % len(variants)]


def document(blocks: int, size: int) -> str:
    """Build exactly `blocks` Markdown blocks and `size` ASCII bytes."""
    values = [block(i) for i in range(1, blocks + 1)]
    missing = size - sum(len(value) for value in values)
    if missing < 0:
        raise ValueError(f"{blocks} blocks exceed {size} bytes")
    each, remainder = divmod(missing, blocks)
    # Add deterministic trailing spaces to each block's final line. This pads
    # bytes without introducing extra Markdown blocks or one pathological long
    # whitespace line in the Stress fixture.
    return "".join(
        value[:-2] + " " * (each + (index < remainder)) + "\n\n"
        for index, value in enumerate(values)
    )


def main() -> None:
    DATA.mkdir(exist_ok=True)
    specs = {
        "small": (5 * 1024, 100),
        "medium": (50 * 1024, 1000),
        "large": (500 * 1024, 10000),
        "stress": (5 * 1024 * 1024, 100000),
    }
    manifest = []
    for name, (size, blocks) in specs.items():
        path = DATA / f"{name}.md"
        path.write_text(document(blocks, size), encoding="utf-8")
        manifest.append(f"{name}\t{size}\t{blocks}\t{path.name}")
    (DATA / "MANIFEST.tsv").write_text("name\tbytes\tblocks\tfile\n" + "\n".join(manifest) + "\n")
    (DATA / ".generated").write_text("generated by scripts/generate_fixtures.py\n")


if __name__ == "__main__":
    main()
