#!/usr/bin/env python3
"""Generate deterministic Markdown fixtures used by every implementation."""

from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
DATA = ROOT / "data"


def block(index: int) -> str:
    return (
        f"## Block {index:05d}\n\n"
        "Text **bold** *em*.\n\n"
        "- item\n\n"
    )


def document(blocks: int) -> str:
    return "# Benchmark document\n\n" + "".join(block(i) for i in range(1, blocks + 1))


def fit_size(text: str, size: int) -> str:
    """Keep a fixture at exactly size bytes without cutting UTF-8."""
    if len(text.encode()) >= size:
        raw = text.encode()[:size]
        return raw.decode("utf-8", "ignore").ljust(size, " ")
    filler = "\n<!-- deterministic filler: 0123456789abcdef -->\n"
    while len(text.encode()) < size:
        remaining = size - len(text.encode())
        text += filler[:remaining]
    return text


def main() -> None:
    DATA.mkdir(exist_ok=True)
    specs = {
        "small": (5 * 1024, 100),
        "medium": (50 * 1024, 1000),
        "large": (500 * 1024, 10000),
        "stress": (5 * 1024 * 1024, 100000),
    }
    manifest = []
    for name, (size, blocks) in specs.items():
        path = DATA / f"{name}.md"
        path.write_text(fit_size(document(blocks), size), encoding="utf-8")
        manifest.append(f"{name}\t{size}\t{blocks}\t{path.name}")
    (DATA / "MANIFEST.tsv").write_text("name\tbytes\tblocks\tfile\n" + "\n".join(manifest) + "\n")
    (DATA / ".generated").write_text("generated by scripts/generate_fixtures.py\n")


if __name__ == "__main__":
    main()
